blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/YOUR_USERNAME/blocklink/discussions/categories/feature-request
    about: Discuss ideas for new features or enhancements. It will be converted to a GitHub issue when we commit to building those changes or are helping a community member contribute their own changes.
  - name: Ask a Question
    url: https://github.com/YOUR_USERNAME/blocklink/discussions/category_choices
    about: Ask questions and discuss with other community members.
