#!/bin/bash

set -e

if [ "$1" = configure ]; then

    INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -sf /usr/share/linknode/linknode /usr/bin/linknode

    if [ "systemd" == "$INITSYS" ]; then

        # Clean up old service files if they exist
        rm -f /etc/systemd/system/linknode.service \
              /usr/lib/systemd/system/linknode.service \
              /usr/lib/systemd/user/linknode.service >/dev/null 2>&1

        # Prepare systemd service
        mkdir -p /usr/lib/systemd/system/
        cp /usr/share/linknode/files/systemd/linknode.service /usr/lib/systemd/system/linknode.service

        # Fix for older Ubuntu (Exec format issue)
        if [ -e /usr/bin/pkill ]; then
            sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/linknode.service
        fi

        # Reload and start service
        systemctl daemon-reload
        systemctl enable linknode
        systemctl start linknode
    fi
fi
